spring.application.name=lr4
spring.datasource.url=jdbc:postgresql://localhost:5432/lr1
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
server.servlet.context-path=/

spring.mail.host=172.27.168.185
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

spring.activemq.packages.trust-all=true
# Optional
logging.level.org.springframework.mail=DEBUG
