spring.application.name=lr3
spring.datasource.url=jdbc:postgresql://localhost:5432/lr1
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
server.servlet.context-path=/